import { PropertyConfig } from "../types";

export const propertySchema: PropertyConfig[] = [
  {
    key: "text",
    name: "Text Content",
    type: "textarea",
    target: "props",
    defaultValue: "This is a block of text.",
    section: "Content",
  },
  {
    key: "width",
    name: "Width",
    type: "text",
    target: "styles",
    defaultValue: "auto",
    section: "Layout",
  },
  {
    key: "height",
    name: "Height",
    type: "text",
    target: "styles",
    defaultValue: "auto",
    section: "Layout",
  },
  {
    key: "margin",
    name: "Margin",
    type: "text",
    target: "styles",
    defaultValue: "0px",
    section: "Layout",
  },
  {
    key: "fontSize",
    name: "Font Size",
    type: "text",
    target: "styles",
    defaultValue: "16px",
    section: "Typography",
  },
  {
    key: "fontWeight",
    name: "Weight",
    type: "select",
    target: "styles",
    defaultValue: "400",
    options: [
      { label: "Light (300)", value: "300" },
      { label: "Normal (400)", value: "400" },
      { label: "Medium (500)", value: "500" },
      { label: "Semibold (600)", value: "600" },
      { label: "Bold (700)", value: "700" },
    ],
    section: "Typography",
  },
  {
    key: "textAlign",
    name: "Text Align",
    type: "select",
    target: "styles",
    defaultValue: "left",
    options: [
      { label: "Left", value: "left" },
      { label: "Center", value: "center" },
      { label: "Right", value: "right" },
      { label: "Justify", value: "justify" },
    ],
    section: "Typography",
  },
  {
    key: "lineHeight",
    name: "Line Height",
    type: "text",
    target: "styles",
    defaultValue: "1.5",
    section: "Typography",
  },
  {
    key: "color",
    name: "Text Color",
    type: "color",
    target: "styles",
    defaultValue: "#ffffff",
    section: "Styles",
  },
];
