import { PropertyConfig } from "../types";

export const propertySchema: PropertyConfig[] = [
  {
    key: "name",
    name: "Container Name",
    type: "text",
    target: "props",
    defaultValue: "Container",
    section: "Content",
  },
  {
    key: "display",
    name: "Display",
    type: "select",
    target: "styles",
    defaultValue: "flex",
    options: [
      { label: "Flexbox", value: "flex" },
      { label: "Block", value: "block" },
      { label: "None", value: "none" },
    ],
    section: "Layout",
  },
  {
    key: "flexDirection",
    name: "Direction",
    type: "select",
    target: "styles",
    defaultValue: "column",
    options: [
      { label: "Row (Horizontal)", value: "row" },
      { label: "Column (Vertical)", value: "column" },
    ],
    section: "Layout",
  },
  {
    key: "justifyContent",
    name: "Justify Content",
    type: "select",
    target: "styles",
    defaultValue: "flex-start",
    options: [
      { label: "Start", value: "flex-start" },
      { label: "Center", value: "center" },
      { label: "End", value: "flex-end" },
      { label: "Space Between", value: "space-between" },
      { label: "Space Around", value: "space-around" },
    ],
    section: "Layout",
  },
  {
    key: "alignItems",
    name: "Align Items",
    type: "select",
    target: "styles",
    defaultValue: "stretch",
    options: [
      { label: "Stretch", value: "stretch" },
      { label: "Start", value: "flex-start" },
      { label: "Center", value: "center" },
      { label: "End", value: "flex-end" },
    ],
    section: "Layout",
  },
  {
    key: "gap",
    name: "Gap (e.g. 12px)",
    type: "text",
    target: "styles",
    defaultValue: "12px",
    section: "Layout",
  },
  {
    key: "padding",
    name: "Padding (e.g. 16px)",
    type: "text",
    target: "styles",
    defaultValue: "24px",
    section: "Layout",
  },
  {
    key: "margin",
    name: "Margin (e.g. 0px)",
    type: "text",
    target: "styles",
    defaultValue: "0px",
    section: "Layout",
  },
  {
    key: "width",
    name: "Width (e.g. 100%, 300px)",
    type: "text",
    target: "styles",
    defaultValue: "auto",
    section: "Layout",
  },
  {
    key: "height",
    name: "Height (e.g. auto, 200px)",
    type: "text",
    target: "styles",
    defaultValue: "auto",
    section: "Layout",
  },
  {
    key: "minHeight",
    name: "Min Height",
    type: "text",
    target: "styles",
    defaultValue: "80px",
    section: "Layout",
  },
  {
    key: "backgroundColor",
    name: "Background Color",
    type: "color",
    target: "styles",
    defaultValue: "transparent",
    section: "Styles",
  },
  {
    key: "borderRadius",
    name: "Border Radius (e.g. 8px)",
    type: "text",
    target: "styles",
    defaultValue: "8px",
    section: "Styles",
  },
  {
    key: "borderWidth",
    name: "Border Width",
    type: "text",
    target: "styles",
    defaultValue: "1px",
    section: "Styles",
  },
  {
    key: "borderColor",
    name: "Border Color",
    type: "color",
    target: "styles",
    defaultValue: "#4b5563",
    section: "Styles",
  },
  {
    key: "borderStyle",
    name: "Border Style",
    type: "select",
    target: "styles",
    defaultValue: "dashed",
    options: [
      { label: "None", value: "none" },
      { label: "Solid", value: "solid" },
      { label: "Dashed", value: "dashed" },
      { label: "Dotted", value: "dotted" },
    ],
    section: "Styles",
  },
];
