import { PropertyConfig } from "../types";

export const propertySchema: PropertyConfig[] = [
  {
    key: "text",
    name: "Button Text",
    type: "string",
    target: "props",
    defaultValue: "Button",
    category: "Content",
    section: "Content",
  },
  {
    key: "type",
    name: "Type",
    type: "enum",
    target: "props",
    defaultValue: "default",
    enum: ["default", "primary", "dashed", "link", "text"],
    category: "Content",
    section: "Content",
  },
  {
    key: "size",
    name: "Size",
    type: "enum",
    target: "props",
    defaultValue: "middle",
    enum: ["small", "middle", "large"],
    category: "Content",
    section: "Content",
  },
  {
    key: "shape",
    name: "Shape",
    type: "enum",
    target: "props",
    defaultValue: "default",
    enum: ["default", "circle", "round"],
    category: "Content",
    section: "Content",
  },
  {
    key: "danger",
    name: "Danger",
    type: "boolean",
    target: "props",
    defaultValue: false,
    category: "Content",
    section: "Content",
  },
  {
    key: "ghost",
    name: "Ghost",
    type: "boolean",
    target: "props",
    defaultValue: false,
    category: "Content",
    section: "Content",
  },
  {
    key: "block",
    name: "Block",
    type: "boolean",
    target: "props",
    defaultValue: false,
    category: "Content",
    section: "Content",
  },
  {
    key: "disabled",
    name: "Disabled",
    type: "boolean",
    target: "props",
    defaultValue: false,
    category: "Content",
    section: "Content",
  },
  {
    key: "loading",
    name: "Loading",
    type: "boolean",
    target: "props",
    defaultValue: false,
    category: "Content",
    section: "Content",
  },
  {
    key: "icon",
    name: "Icon",
    type: "string",
    target: "props",
    defaultValue: "",
    category: "Content",
    section: "Content",
  },
  {
    key: "href",
    name: "Href",
    type: "string",
    target: "props",
    defaultValue: "",
    category: "Content",
    section: "Content",
  },
  {
    key: "target",
    name: "Target",
    type: "string",
    target: "props",
    defaultValue: "",
    category: "Content",
    section: "Content",
  },
];
