import { PropertyConfig } from "../types";

export const propertySchema: PropertyConfig[] = [
  {
    key: "text",
    name: "Button Text",
    type: "text",
    target: "props",
    defaultValue: "Click Me",
    section: "Content",
  },
  {
    key: "width",
    name: "Width",
    type: "text",
    target: "styles",
    defaultValue: "auto",
    section: "Layout",
  },
  {
    key: "height",
    name: "Height",
    type: "text",
    target: "styles",
    defaultValue: "auto",
    section: "Layout",
  },
  {
    key: "padding",
    name: "Padding",
    type: "text",
    target: "styles",
    defaultValue: "8px 16px",
    section: "Layout",
  },
  {
    key: "margin",
    name: "Margin",
    type: "text",
    target: "styles",
    defaultValue: "0px",
    section: "Layout",
  },
  {
    key: "fontSize",
    name: "Font Size",
    type: "text",
    target: "styles",
    defaultValue: "14px",
    section: "Typography",
  },
  {
    key: "fontWeight",
    name: "Weight",
    type: "select",
    target: "styles",
    defaultValue: "500",
    options: [
      { label: "Normal", value: "400" },
      { label: "Medium", value: "500" },
      { label: "Semibold", value: "600" },
      { label: "Bold", value: "700" },
    ],
    section: "Typography",
  },
  {
    key: "color",
    name: "Text Color",
    type: "color",
    target: "styles",
    defaultValue: "#ffffff",
    section: "Styles",
  },
  {
    key: "backgroundColor",
    name: "Background Color",
    type: "color",
    target: "styles",
    defaultValue: "#3b82f6",
    section: "Styles",
  },
  {
    key: "borderRadius",
    name: "Border Radius",
    type: "text",
    target: "styles",
    defaultValue: "6px",
    section: "Styles",
  },
  {
    key: "borderColor",
    name: "Border Color",
    type: "color",
    target: "styles",
    defaultValue: "#2563eb",
    section: "Styles",
  },
  {
    key: "borderWidth",
    name: "Border Width",
    type: "text",
    target: "styles",
    defaultValue: "1px",
    section: "Styles",
  },
  {
    key: "borderStyle",
    name: "Border Style",
    type: "select",
    target: "styles",
    defaultValue: "solid",
    options: [
      { label: "None", value: "none" },
      { label: "Solid", value: "solid" },
      { label: "Dashed", value: "dashed" },
    ],
    section: "Styles",
  },
];
