import { PropertyConfig } from "../types";

export const propertySchema: PropertyConfig[] = [
  // Content Section
  {
    key: "loading",
    name: "Loading Status",
    type: "switch",
    target: "props",
    defaultValue: true,
    section: "Content",
  },
  {
    key: "loadingType",
    name: "Spinner Type",
    type: "select",
    target: "props",
    defaultValue: "Spinner",
    options: [
      { label: "Spinner (Classic)", value: "Spinner" },
      { label: "Bouncing Dots", value: "Dots" },
      { label: "Circular Ring", value: "Circular" },
      { label: "Progress Bar", value: "ProgressBar" },
      { label: "Skeleton Screen", value: "Skeleton" },
    ],
    section: "Content",
  },
  {
    key: "spinnerPosition",
    name: "Spinner Position",
    type: "select",
    target: "props",
    defaultValue: "center",
    options: [
      { label: "Center", value: "center" },
      { label: "Top", value: "top" },
      { label: "Bottom", value: "bottom" },
      { label: "Left Side", value: "left" },
      { label: "Right Side", value: "right" },
    ],
    section: "Content",
  },
  {
    key: "text",
    name: "Loading Text",
    type: "text",
    target: "props",
    defaultValue: "Loading...",
    section: "Content",
  },
  {
    key: "delay",
    name: "Delay (ms)",
    type: "number",
    target: "props",
    defaultValue: 0,
    min: 0,
    max: 10000,
    step: 50,
    section: "Content",
  },

  // Display Section
  {
    key: "fullScreen",
    name: "Full Screen Overlay",
    type: "switch",
    target: "props",
    defaultValue: false,
    section: "Layout",
  },
  {
    key: "overlay",
    name: "Parent Overlay",
    type: "switch",
    target: "props",
    defaultValue: false,
    section: "Layout",
  },
  {
    key: "blurBackground",
    name: "Blur Background",
    type: "switch",
    target: "props",
    defaultValue: false,
    section: "Layout",
  },
  {
    key: "blockInteraction",
    name: "Block Interaction",
    type: "switch",
    target: "props",
    defaultValue: true,
    section: "Layout",
  },
  {
    key: "animationType",
    name: "Animation Style",
    type: "select",
    target: "props",
    defaultValue: "fade",
    options: [
      { label: "None", value: "none" },
      { label: "Fade In", value: "fade" },
      { label: "Scale Up", value: "scale" },
      { label: "Rotate Speed", value: "rotate" },
      { label: "Pulse Wave", value: "pulse" },
    ],
    section: "Layout",
  },

  // Skeleton Configuration
  {
    key: "skeletonType",
    name: "Skeleton Layout",
    type: "select",
    target: "props",
    defaultValue: "default",
    options: [
      { label: "Default Layout", value: "default" },
      { label: "Button Mockup", value: "button" },
      { label: "Card Grid", value: "card" },
      { label: "Table Mockup", value: "table" },
    ],
    section: "Content",
  },
  {
    key: "skeletonRows",
    name: "Skeleton Rows",
    type: "number",
    target: "props",
    defaultValue: 4,
    min: 1,
    max: 20,
    section: "Content",
  },
  {
    key: "skeletonAvatar",
    name: "Show Skeleton Avatar",
    type: "switch",
    target: "props",
    defaultValue: true,
    section: "Content",
  },
  {
    key: "skeletonParagraph",
    name: "Show Skeleton Text",
    type: "switch",
    target: "props",
    defaultValue: true,
    section: "Content",
  },

  // Styling properties
  {
    key: "size",
    name: "Size",
    type: "select",
    target: "props",
    defaultValue: "medium",
    options: [
      { label: "Small", value: "small" },
      { label: "Medium", value: "medium" },
      { label: "Large", value: "large" },
    ],
    section: "Styles",
  },
  {
    key: "color",
    name: "Loading Color",
    type: "color",
    target: "props",
    defaultValue: "#3b82f6",
    section: "Styles",
  },
  {
    key: "backgroundColor",
    name: "Overlay Background Color",
    type: "color",
    target: "props",
    defaultValue: "rgba(0, 0, 0, 0.4)",
    section: "Styles",
  },
  {
    key: "opacity",
    name: "Opacity (0 to 1)",
    type: "text",
    target: "props",
    defaultValue: "1",
    section: "Styles",
  },
  {
    key: "borderRadius",
    name: "Border Radius",
    type: "text",
    target: "props",
    defaultValue: "6px",
    section: "Styles",
  },
  {
    key: "padding",
    name: "Padding",
    type: "text",
    target: "props",
    defaultValue: "16px",
    section: "Styles",
  },
  {
    key: "zIndex",
    name: "Z-index",
    type: "text",
    target: "props",
    defaultValue: "50",
    section: "Styles",
  },
];
