import { PropertyConfig } from "../types";

export const propertySchema: PropertyConfig[] = [
  // Layout section
  {
    key: "direction",
    name: "Direction",
    type: "select",
    target: "props",
    defaultValue: "row",
    options: [
      { label: "Row (Horizontal)", value: "row" },
      { label: "Row Reverse", value: "row-reverse" },
      { label: "Column (Vertical)", value: "column" },
      { label: "Column Reverse", value: "column-reverse" },
    ],
    section: "Layout",
  },
  {
    key: "justifyContent",
    name: "Justify Content",
    type: "select",
    target: "props",
    defaultValue: "flex-start",
    options: [
      { label: "Flex Start", value: "flex-start" },
      { label: "Center", value: "center" },
      { label: "Flex End", value: "flex-end" },
      { label: "Space Between", value: "space-between" },
      { label: "Space Around", value: "space-around" },
      { label: "Space Evenly", value: "space-evenly" },
    ],
    section: "Layout",
  },
  {
    key: "alignItems",
    name: "Align Items",
    type: "select",
    target: "props",
    defaultValue: "stretch",
    options: [
      { label: "Stretch", value: "stretch" },
      { label: "Flex Start", value: "flex-start" },
      { label: "Center", value: "center" },
      { label: "Flex End", value: "flex-end" },
      { label: "Baseline", value: "baseline" },
    ],
    section: "Layout",
  },
  {
    key: "wrap",
    name: "Wrap",
    type: "select",
    target: "props",
    defaultValue: "nowrap",
    options: [
      { label: "No Wrap", value: "nowrap" },
      { label: "Wrap", value: "wrap" },
      { label: "Wrap Reverse", value: "wrap-reverse" },
    ],
    section: "Layout",
  },
  {
    key: "rowGap",
    name: "Row Gap (e.g. 16px, 1rem)",
    type: "text",
    target: "props",
    defaultValue: "16px",
    section: "Layout",
  },
  {
    key: "columnGap",
    name: "Column Gap (e.g. 16px, 1rem)",
    type: "text",
    target: "props",
    defaultValue: "16px",
    section: "Layout",
  },
  {
    key: "width",
    name: "Width Type",
    type: "select",
    target: "props",
    defaultValue: "100%",
    options: [
      { label: "Auto", value: "auto" },
      { label: "Fit Content", value: "fit-content" },
      { label: "100%", value: "100%" },
      { label: "Custom", value: "custom" },
    ],
    section: "Layout",
  },
  {
    key: "customWidth",
    name: "Custom Width (e.g. 300px)",
    type: "text",
    target: "props",
    defaultValue: "",
    section: "Layout",
  },
  {
    key: "height",
    name: "Height Type",
    type: "select",
    target: "props",
    defaultValue: "auto",
    options: [
      { label: "Auto", value: "auto" },
      { label: "Fit Content", value: "fit-content" },
      { label: "100%", value: "100%" },
      { label: "Custom", value: "custom" },
    ],
    section: "Layout",
  },
  {
    key: "customHeight",
    name: "Custom Height (e.g. 200px)",
    type: "text",
    target: "props",
    defaultValue: "",
    section: "Layout",
  },
  {
    key: "paddingTop",
    name: "Padding Top",
    type: "text",
    target: "props",
    defaultValue: "16px",
    section: "Layout",
  },
  {
    key: "paddingRight",
    name: "Padding Right",
    type: "text",
    target: "props",
    defaultValue: "16px",
    section: "Layout",
  },
  {
    key: "paddingBottom",
    name: "Padding Bottom",
    type: "text",
    target: "props",
    defaultValue: "16px",
    section: "Layout",
  },
  {
    key: "paddingLeft",
    name: "Padding Left",
    type: "text",
    target: "props",
    defaultValue: "16px",
    section: "Layout",
  },
  {
    key: "marginTop",
    name: "Margin Top",
    type: "text",
    target: "props",
    defaultValue: "0px",
    section: "Layout",
  },
  {
    key: "marginRight",
    name: "Margin Right",
    type: "text",
    target: "props",
    defaultValue: "0px",
    section: "Layout",
  },
  {
    key: "marginBottom",
    name: "Margin Bottom",
    type: "text",
    target: "props",
    defaultValue: "0px",
    section: "Layout",
  },
  {
    key: "marginLeft",
    name: "Margin Left",
    type: "text",
    target: "props",
    defaultValue: "0px",
    section: "Layout",
  },

  // Styles section
  {
    key: "backgroundColor",
    name: "Background Color",
    type: "color",
    target: "props",
    defaultValue: "transparent",
    section: "Styles",
  },
  {
    key: "backgroundImage",
    name: "Background Image URL",
    type: "text",
    target: "props",
    defaultValue: "",
    section: "Styles",
  },
  {
    key: "borderWidth",
    name: "Border Width",
    type: "text",
    target: "props",
    defaultValue: "1px",
    section: "Styles",
  },
  {
    key: "borderStyle",
    name: "Border Style",
    type: "select",
    target: "props",
    defaultValue: "dashed",
    options: [
      { label: "None", value: "none" },
      { label: "Solid", value: "solid" },
      { label: "Dashed", value: "dashed" },
      { label: "Dotted", value: "dotted" },
    ],
    section: "Styles",
  },
  {
    key: "borderColor",
    name: "Border Color",
    type: "color",
    target: "props",
    defaultValue: "#4b5563",
    section: "Styles",
  },
  {
    key: "borderRadius",
    name: "Border Radius",
    type: "text",
    target: "props",
    defaultValue: "8px",
    section: "Styles",
  },
  {
    key: "overflow",
    name: "Overflow",
    type: "select",
    target: "props",
    defaultValue: "visible",
    options: [
      { label: "Visible", value: "visible" },
      { label: "Hidden", value: "hidden" },
      { label: "Auto", value: "auto" },
      { label: "Scroll", value: "scroll" },
    ],
    section: "Styles",
  },
];
